server {
    listen 80;
    server_name localhost;

    # Onde os arquivos do build do react ficarão
    root /usr/share/nginx/html;
    index index.html;

    # Queda para o index.html quando a rota não for um arquivo existente (Necessário para o React Router)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Desligar logs de acesso para arquivos estáticos para não poluir
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires max;
        log_not_found off;
    }
}
